server:
  port: 8080

logging:
  level:
    root: warn #??????? ??????????????
    ru: debug  #???????? ???? ??????????

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres #???? ? ???? ??????
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver #??????? ??? ?????? ???????? ?? ???????????? ? ???? ??????
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
jwt:
  secret:
    access: qBTmv4oXFFR2GwjexDJ4thhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==
    refresh: zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKTJP/wAzKawB8F9rOMNg==

