server:
  port: 8080

logging:
  level:
    root: warn #??????? ??????????????
    ru: debug  #???????? ???? ??????????

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/neftLink #???? ? ???? ??????
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver #??????? ??? ?????? ???????? ?? ???????????? ? ???? ??????
