CREATE TABLE IF NOT EXISTS BASE
(
    ID         UUID         NOT NULL PRIMARY KEY,
    NAME       VARCHAR(100) NOT NULL UNIQUE,
    ADDRESS    VARCHAR(200),
    IS_VISIBLE BOOLEAN
);

CREATE TABLE IF NOT EXISTS GAS
(
    ID         UUID                NOT NULL PRIMARY KEY,
    GAS_TYPE   VARCHAR(100) UNIQUE NOT NULL,
    IS_VISIBLE BOOLEAN
);

CREATE TABLE IF NOT EXISTS ROLE
(
    ID        UUID        NOT NULL PRIMARY KEY,
    ROLE_NAME VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS USERS
(
    ID       UUID         NOT NULL PRIMARY KEY,
    NAME     VARCHAR(50),
    INN      INTEGER      NOT NULL UNIQUE,
    EMAIL    VARCHAR(50)  NOT NULL UNIQUE,
    PASSWORD VARCHAR(200) NOT NULL,
    COMPANY  VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS USERS_ROLES
(
    USER_ID UUID NOT NULL,
    ROLE_ID UUID NOT NULL
);

CREATE TABLE ORDERS
(
    ID          UUID      PRIMARY KEY,
    COST        BIGINT,
    CREATE_DATE TIMESTAMP NOT NULL,
    UPDATE_DATE TIMESTAMP,
    GAS_ID      UUID      NOT NULL,
    BASE_ID     UUID      NOT NULL,
    USER_ID     UUID      NOT NULL,
    IS_VISIBLE  BOOLEAN,
    foreign key (GAS_ID) references GAS (id),
    foreign key (BASE_ID) references BASE (id),
    foreign key (USER_ID) references USERS (id)
);